# Bodega Configuration File
# Combines settings for PB&J pipeline and soda document storage

# PB&J Pipeline Configuration
pbj:
  # PDF Processing Settings
  llamaparse_api_key: "${LLAMAPARSE_API_KEY}"
  use_premium_mode: false
  
  # OpenAI Settings
  openai_api_key: "${OPENAI_API_KEY}"
  openai_model: "gpt-4"
  max_tokens: 6000  # Reduced from 8000 to avoid token limit issues
  
  # Output Settings
  output_base_dir: "processed_documents"
  create_timestamped_folders: true
  enable_verbose_logging: true
  page_separator: "\n---\n"
  max_timeout: 180

# Soda (Document Store) Configuration
soda:
  # AWS Settings
  aws_region: "${AWS_REGION:-us-east-1}"
  bucket_name: "${DOC_BUCKET}"
  
  # Document States
  default_state: "raw"
  enable_state_validation: true
  
  # Caching
  enable_cache: true
  cache_ttl_seconds: 3600
  
  # Performance
  max_concurrent_operations: 10
  retry_attempts: 3
  retry_delay_seconds: 1

# Inspector (Manual Review) Configuration
inspector:
  auto_launch: false
  port: 8501
  enable_editing: true
  approval_required: true
  portfolio_tags: ["ts knee", "knee", "hips"]
  # Path to processed documents for review
  processed_documents_dir: "processed_documents"

# Bodega Orchestrator Settings
bodega:
  # Processing Settings
  auto_upload_to_aws: true
  generate_doc_ids: true
  
  # Error Handling
  continue_on_pbj_error: false
  continue_on_soda_error: false
  
  # Logging
  log_level: "INFO"
  enable_health_checks: true 